export const tabConfig=[
    {
        icon:'icon-appreciate',
        name:'首页',
        key:'home',
        src:`${weex.config.eros.jsServer}/dist/js/pages/standard/home/index.js`
    },
    {
        icon:'icon-appreciate',
        name:'娱乐',
        key:'entertain',
        src:`${weex.config.eros.jsServer}/dist/js/pages/standard/entertain/index.js`
    },
    {
        icon:'icon-appreciate',
        name:'发现',
        key:'discover',
        src:`${weex.config.eros.jsServer}/dist/js/pages/standard/home/index.js`
    },
    {
        icon:'icon-appreciate',
        name:'我的',
        key:'mine',
        src:`${weex.config.eros.jsServer}/dist/js/pages/standard/home/index.js`
    }
]
